<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Google.Protobuf" Version="3.35.1" />
        <PackageVersion Include="Grpc.Tools" Version="2.83.0" />
        <PackageVersion Include="MSTest" Version="4.3.3" />
    </ItemGroup>
</Project>
