<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Compuse.Protocol</RootNamespace>
        <AssemblyName>Compuse.Protocol</AssemblyName>
        <OutputType>Library</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Grpc.Tools">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <ProjectReference Include="..\Compuse.Contracts\Compuse.Contracts.csproj" />
        <ProjectReference Include="..\Compuse.Requests\Compuse.Requests.csproj" />
        <Protobuf Include="..\..\proto\compuse\v1\operation_result.proto" GrpcServices="None" />
        <Protobuf Include="..\..\proto\compuse\v1\drop_files.proto" GrpcServices="None" />
    </ItemGroup>
</Project>
